'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993, 1994 Peter Miller.
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" MANIFEST: manual entry for 'aegis -Build' command
.\"
.so z_name.so
.TH "\*(n) -Build" 1 \*(N)
.SH NAME
\*(n) -Build \- build a change
.SH SYNOPSIS
.B \*(n)
.B -Build
[
.IR option ...
][
.IR filename ...
]
.br
.B \*(n)
.B -Build
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -Build
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -Build
command is used to
build a project.
The project configuration file is consulted for the
appropriate build command,
and that command is executed
(see 
.IR aepconf (5)
for more information.)
Output of the command is automatically logged to the
.I \*(n).log
file at the root of the development directory tree.
The build command will be executed with its current directory being
the root of the development directory,
irrespective of there the
.I "\*(n) -Build"
command was executed.
.PP
If the change is in the
.I "being integrated"
state,
references to the development directory, above,
should be read as the integration directory.
Integration build commands are executed with the user and group
set to the project's owning user and group.
That is,
it is not necessary for an integrator to log in as someone else,
the project account for instance,
in order to do an integration.
.so o_bld_lk.so
.so o_symlnk.so
.SH PARTIAL BUILD
If files are named on the command line,
these files are appended to the build command.
This is known as a partial build.
Partial builds are not legal in the
.I "being integrated"
state,
but can often be useful in the
.I "being developed"
state.
Partial builds are not recorded in the change status,
because builds are decoupled from aegis it is not
possible for aegis to know if any set of partial builds is equivalent
to a full build.
.so z_intuit.so
.PP
Warning:
no locks are taken for a partial build,
not even the build lock.
.SH OPTIONS
The following options are understood:
.so o_change.so
.so o_help.so
.so o_list.so
.so o_nolog.so
.so o_project.so
.so o_terse.so
.so o_verbose.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aeb '\*(n) -b \e!* -v'
sh$	aeb(){\*(n) -b $* -v}
.fi
.SH ERRORS
It is an error if
the change is not assigned to the current user.
.br
It is an error if
the change is not in one of the
.I "being developed"
or
.I "being integrated"
states.
.br
It is an error if
a partial build is requested and the change is in the
.I "being integrated"
state.
.so z_exit.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aedb (1)
begin development of a change
.TP 8n
.IR aeib (1)
begin integration of a change
.TP 8n
.IR aet (1)
run tests
.TP 8n
.IR aepconf (5)
project configuration file format
.TP 8n
.IR aeuconf (5)
user configuration file format
.so z_cr.so
