'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993 Peter Miller.
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" MANIFEST: manual entry for 'aegis -New_File' command
.\"
.so z_name.so
.TH "\*(n) -New_File" 1 \*(N)
.SH NAME
\*(n) -New_File \- add new files to a change
.SH SYNOPSIS
.B \*(n)
.B -New_File
.IR file-name ...
[
.IR option ...
]
.br
.B \*(n)
.B -New_File
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -New_File
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -New_File
command is used to
add new files to a change.
.so z_intuit.so
.PP
The named files will be
added to the list of files in the change.
For each file named,
a new file is created in the development directory,
if it does not exist already.
The
.I config
file will be searched for a template for the new file.
If a template is found,
the new file will be initialized to the template,
otherwise it will be created empty.
If the file already exists,
it will not be altered.
See
.IR aepconf (5)
for more information.
.SH OPTIONS
The following options are understood
.so o_change.so
.so o_help.so
.so o_list.so
.so o_nolog.so
.so o_project.so
.so o_terse.so
.so o_verbose.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aenf '\*(n) -nf \e!* -v'
sh$	aenf(){\*(n) -nf $* -v}
.fi
.SH ERRORS
It is an error if
the change is not in the 'being_developed' state.
.br
It is an error if
the change is not assigned to the current user.
.br
It is an error if
the file is already part of the change.
.br
It is an error if
the file is already part of the baseline.
.so z_exit.so
.so z_cr.so
