'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993 Peter Miller.
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" MANIFEST: manual entry for 'aegis -New_Test' command
.\"
.so z_name.so
.TH "\*(n) -New_Test" 1 \*(N)
.SH NAME
\*(n) -New_Test \- add a new test to a change
.SH SYNOPSIS
.B \*(n)
.B -New_Test
[
.IR option ...
]
.br
.B \*(n)
.B -New_Test
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -New_Test
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -New_Test
command is used to
add a new test to a change.
A new file is created in the development directory.
The
.I config
file will be searched for a template for the new file.
If a template is found,
the new file will be initialized to the template,
otherwise it will be created empty.
See
.IR aepconf (5)
for more information.
.PP
New tests default to automatic unless otherwise specified.
.PP
It is not possible to choose your own test number,
or test file name.
All tests within a project are numbered uniquely.
Test files are named as "\fItest/XX/tXXXX[am].sh\fP",
where
.I XX
is the first 2 digits of the test number,
.I XXXX
is the whole test number, and
.I [am] 
is \f(CWa\fP for automatic tests
and \f(CWm\fP for manual tests.
.SH OPTIONS
The following options are understood;
.so o_auto.so
.so o_change.so
.so o_help.so
.so o_list.so
.so o_manual.so
.so o_project.so
.so o_terse.so
.so o_verbose.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aent '\*(n) -nt \e!* -v'
sh$	aent(){\*(n) -nt $* -v}
.fi
.SH ERRORS
It is an error if
the change is not in the 'being_developed' state.
.br
It is an error if
the change is not assigned to the current user.
.so z_exit.so
.so z_cr.so
