'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993 Peter Miller.
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" MANIFEST: manual entry for 'aegis -Remove_Developer' command
.\"
.so z_name.so
.TH "\*(n) -Remove_Developer" 1 \*(N)
.SH NAME
\*(n) -Remove_Developer \- remove developers from a project
.SH SYNOPSIS
.B \*(n)
.B -Remove_Developer
.IR user-name ...
[
.IR option ...
]
.br
.B \*(n)
.B -Remove_Developer
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -Remove_Developer
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -Remove_Developer
command is used to
remove developers from a project.
.SH OPTIONS
The following options are understood:
.so o_help.so
.so o_list.so
.so o_project.so
.so o_terse.so
.so o_verbose.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aerd '\*(n) -rd \e!* -v'
sh$	aerd(){\*(n) -rd $* -v}
.fi
.SH ERRORS
It is an error if
the current user is not an administrator of the project.
.so z_exit.so
.so z_cr.so
