.\"
.\"	aegis - project change supervisor
.\"	Copyright (C) 1995 Peter Miller;
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" MANIFEST: input for archive/Aegis.lsm
.\"
.\" LSM = Linux Software Module, an archive description file
.\"
.\" Descriptions of the LSM file format can be found in the
.\" /pub/Linux/docs directories of sunsite.unc.edu and tsx-11.mit.edu.
.\"
.ad l
.hy 0
.de SH
.in 0
.br
\\$1
'in 8n
..
.so ../doc/version.so
.SH Begin3
.SH Title:
Aegis
.SH Version:
\*(v)
.SH Entered-date:
.ds MO1 JAN
.ds MO2 FEB
.ds MO3 MAR
.ds MO4 APR
.ds MO5 MAY
.ds MO6 JUN
.ds MO7 JUL
.ds MO8 AUG
.ds MO9 SEP
.ds MO10 OCT
.ds MO11 NOV
.ds MO12 DEC
\n[dy]\*[MO\n[mo]]\n[yr]
.SH Description:
Aegis is a transaction-based software configuration management system.
It provides a framework within which
a team of developers may work on many changes to a
program independently, and Aegis coordinates integrating
these changes back into the master source of the program,
with as little disruption as possible.
.sp
Aegis runs on almost any flavor of UNIX.
Self-configuring.
There are no modifications required to compile it for Linux.
.SH Keywords:
transaction based software configuration management,
version control
.SH Author:
pmiller@agso.gov.au (Peter Miller)
.SH Primary-site:
ftp.nau.edu /pub/Aegis
.br
aegis.\*(v).README
.br
aegis.\*(v).tar.gz
.br
aegis.\*(v).ps.gz
.SH Copying-policy:
GPL
.SH End
