'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991-1995, 2006-2008 Peter Miller
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program. If not, see
.\"	<http://www.gnu.org/licenses/>.
.\"
.so z_name.so
.TH aecattr 5 \*(N) "Reference Manual"
.SH NAME
aecattr - \*(n) change attributes file
.XX "aecattr(5)" "change attributes file format"
.SH DESCRIPTION
A change attributes file is used to describe the
modifiable portion of a change.
.SH CONTENTS
A change attributes file contains the following fields:
.so aecattr.so
.SH SEE ALSO
.TP 8n
.IR aenc (1)
create a new change
.TP 8n
.IR aeca (1)
modify the attributes of a change
.TP 8n
.IR aegis (5)
\*(n) file format syntax
.TP 8n
.IR aecstate (5)
change state file format
.TP 8n
.IR aepattr (5)
project attributes file format
.so ../man1/z_cr.so
