'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993, 1995, 1999 Peter Miller;
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
.\"
.\" MANIFEST: description of aegis global state file format
.\"
.so z_name.so
.so libdir.so
.TH aegstate 5 \*(N) "Reference Manual"
.SH NAME
aegstate \- \*(n) state file
.XX "aegstate(5)" "global state file format"
.SH SYNOPSIS
\f(CW\*(S)/state\fP
.SH DESCRIPTION
The \*(n) state file
is used to store
the pointers to project directories.
.SH CONTENTS
.TP 8n
where = [{ ... }];
.br
This field is a table relating project name to project directory.
The structure is as follows:
.RS
.TP 8n
project_name = string;
.br
The name of a project.
.TP 8n
directory = string;
.br
Absolute path of the project's directory.
(Only set of \fIaelias_for\fP is not set.)
.TP 8n
alias_for = string;
.br
This is the name of another project, possibly including branch numbers.
It allows you to have shorter or more meaningful project names.
(Only set if \fIdirectory\fP is not set.)
.RE
.SH SEE ALSO
.TP 8n
.IR aegis (5)
\*(n) file format syntax
.so ../man1/z_cr.so
