'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1998 Peter Miller;
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
.\"
.\" MANIFEST: manual page describing the aeclone command.
.\"
.so z_name.so
.TH "\*(n) -clone" 1 \*(N) "Reference Manual" ""
.SH NAME
\*(n) -clone \- make an exact copy of a change
.SH SYNOPSIS
.B \*(n)
.B \-CLone
[
.IR option \&...
]
.I change-number
[
change-number
]
.br
.B \*(n)
.B -CLone
.B -Help
.br
.B \*(n)
.B -CLone
.B -VERSion
.SH DESCRIPTION
The
.I "\*(n) -CLone"
command is used to
create exact replicas of changes.
This is of most use when a change need to be applied to several parallel
branches.
.PP
One change number
.I must
be supplied.  This is the change to be replicated.  If any branch options
are given (see below) the mandatory change number applies to the branch
specified.  If no branch is specified, the change applies to the project
(implicit or explicit).
.PP
If the optional second change number is supplied, this is the change
number to be created to hold the replica; if it is not supplied, the
next available change number will be used.
.PP
If the change to be replicated has been completed, the appropriate
file revisions will be extracted from history; otherwise the files will
be copied from the development directory of the change to be copied.
Be warned: if a file in the change which was cloned subsequently changes,
those changes
.I "will not"
automagicly be tracked.  It is best if changes are cloned at a stable
time, such as one of the states after develop end, or even after integrate pass.
.SH OPTIONS
The following options are understood:
.so o_branch.so
.so o_change.so
.so o_dir.so
.so o_help.so
.so o_list.so
.so o_project.so
.so o_trunk.so
.so o_wait.so
.so o__rules.so
.so z_exit.so
.so z_cr.so
