'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 2002, 2006-2008 Peter Miller
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program. If not, see
.\"	<http://www.gnu.org/licenses/>.
.\"
.so z_name.so
.ds n) aecomplete
.TH "aecomplete" 1 \*(N) "Reference Manual" ""
.SH NAME
aecomplete \- command completion
.XX "aecomplete(1)" "command completion"
.SH SYNOPSIS
.B \*(n)
.I cmd-name
.I incomplete-word
.I previous-word
.SH DESCRIPTION
The
.I "\*(n)"
command is used to
perform command completion for shells.
.PP
See \fIbash\fP(1) for more information about Bash command completion,
and how this command is expected to be executed.
.PP
At present, this is the only shell supported.
The code has been written to be extensible, should other shells have
programmable completion by external programs.
.so z_exit.so
.so z_cr.so
