'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993, 1994, 1997, 1998 Peter Miller;
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
.\"
.\" MANIFEST: manual entry for 'aegis -Develop_End' command
.\"
.so z_name.so
.TH "\*(n) -Develop_End" 1 \*(N) "Reference Manual"
.SH NAME
\*(n) -Develop_End \- complete development of a change
.XX "aede(1)" "complete development of a change"
.SH SYNOPSIS
.B \*(n)
.B -Develop_End
[
.IR option ...
]
.br
.B \*(n)
.B -Develop_End
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -Develop_End
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -Develop_End
command is used to
notify \*(n) of the completion of the development of a change.
.PP
This command checks that you have successfully completed
an '\*(n) -Build' command since any change source file was edited.
See
.IR aeb (1)
for more information.
.PP
This command checks that you have successfully completed
an '\*(n) -DIFFerence' command since any change source file was edited.
See
.IR aed (1)
for more information.
.PP
This command checks that you have successfully completed
an '\*(n) -Test' command
since the last successful build,
unless the change has a
.I test_exempt
attribute.
This command checks that you have successfully completed
an '\*(n) -Test -BaseLine' command,
unless the change has a
.I test_baseline_exempt
attribute.
This command checks that you have successfully completed
an '\*(n) -Test -REGression' command,
unless the change has a
.I test_regression_exempt
attribute.
See
.IR aet (1)
and
.IR aecattr (5)
for more information.
.PP
If the change includes the project
.I config
file,
this command checks project file names,
to make sure they conform to the
.I maximum_filename_length
and
.I posix_filename_charset
field settings.
See
.IR aepconf (5)
for more information.
.PP
Successful execution of the command advances the change
from the
.I "being developed"
state to the
.I "being reviewed"
state.
.PP
Because branches may extend for many months or even years, it is common
for the user who initiated the branch to be no longer with the project,
or even the company.  For this reason, project administrators may end the
development of branches.  For normal changes in this situation, use the
.IR aechown (1)
command.
.PP
The change is no longer considered assigned to the developer.
.SH OPTIONS
The following options are understood:
.so o_change.so
.so o_help.so
.so o_list.so
.so o_project.so
.so o_terse.so
.so o_verbose.so
.so o_wait.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aede '\*(n) -de \e!* -v'
sh$	aede(){\*(n) -de $* -v}
.fi
.SH ERRORS
It is an error if
the change is not assigned to the current user.
.br
It is an error if
The change is not in the
.I "being developed"
state.
.br
It is an error if
there has been no successful
.I "'\*(n) -Build'"
command since a change file was last edited.
.br
It is an error if
there has been no successful
.I "'\*(n) -DIFFerence'"
command since a change file was last edited.
.br
It is an error if
there has been no successful
.I "'\*(n) -Test'"
command since a change file was last edited.
.br
It is an error if
there has been no successful
.I "'\*(n) -Test -BaseLine'"
command since a change file was last edited.
.PP
It is an error if
an read-only file is still copied into the change.
Read-only files are to insulate
a change from the baseline during development;
they must be removed before development may end.
.so z_exit.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aeb (1)
build a change
.TP 8n
.IR aeca (1)
list or modify attributes of a change
.TP 8n
.IR aed (1)
difference a change
.TP 8n
.IR aedb (1)
begin development of a change
.TP 8n
.IR aedeu (1)
recall a change for further development
.TP 8n
.IR aerf (1)
fail a change review
.TP 8n
.IR aerp (1)
pass a change review
.TP 8n
.IR aet (1)
test a change
.TP 8n
.IR aepconf (5)
project configuration file format
.TP 8n
.IR aeuconf (5)
user configuration file format
.so z_cr.so
