'\" t
.\" aegis - project change supervisor
.\" Copyright (C) 2006-2008, 2012 Peter Miller
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.so lib/en/man1/z_name.so
.ds n) aefinish
.TH "aefinish" 1 \*(N) "Reference Manual" ""
.SH NAME
aefinish \- finish a change
.XX "aefinish(1)" "finish a change"
.SH SYNOPSIS
.B \*(n)
[
.IR option \&...
]
.br
.B \*(n)
.B -Help
.br
.B \*(n)
.B -VERSion
.SH DESCRIPTION
The \fI\*(n)\fP command is used to finish development or integration of
a change set.  It examines the state of the change set, and executes the
necessary Aegis commands to advance the change set to the next state.
.SH OPTIONS
The following options are understood:
.so lib/en/man1/o_change.so
.so lib/en/man1/o_help.so
.so lib/en/man1/o_project.so
.so lib/en/man1/o__rules.so
.so lib/en/man1/z_exit.so
.so lib/en/man1/z_cr.so
.\" vim: set ts=8 sw=4 et :
