'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991-1994, 1997-1999, 2001-2008 Peter Miller
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program. If not, see
.\"	<http://www.gnu.org/licenses/>.
.\"
.so z_name.so
.TH \*(n) 1 \*(N) "Reference Manual"
.SH NAME
\*(n) \- project change supervisor
.XX "aegis(1)" "project change supervisor"
.SH SYNOPSIS
.B \*(n)
.I function
[
.IR option ...
]
.br
.B \*(n)
.B -Help
.SH DESCRIPTION
The
.I \*(n)
program
is a transaction base software configuration management system.
It is used to
supervise the development and integration of changes into projects.
.SH FUNCTIONS
The following functions are available:
.TP 8n
.B -Build
.br
The
.I "\*(n) -Build"
command is used to
build a project.
See
.IR aeb (1)
for more information.
.TP 8n
.B -Change_Attributes
.br
The
.I "\*(n) -Change_Attributes"
command is used to
modify the attributes of a change.
See
.IR aeca (1)
for more information.
.TP 8n
.B -Change_Directory
.br
The
.I "\*(n) -Change_Directory"
command is used to
change directory.
See
.IR aecd (1)
for more information.
.TP 8n
.B -Change_Owner
.br
The
.I "\*(n) -Change_Owner"
command is used to
facilitate reassignment of the developer of a change in the
.I "being developed"
state.
See
.IR aechown (1)
for more information.
.TP 8n
.B -CLone
.br
The
.I "\*(n) -CLone"
command is used to
exactly replicate a change, usually on another branch.
See
.IR aeclone (1)
for more information.
.TP 8n
.B -CoPy_file
.br
The
.I "\*(n) -CoPy_file"
command is used to
copy a file into a change.
See
.IR aecp (1)
for more information.
.TP 8n
.B -CoPy_file_Undo
.br
The
.I "\*(n) -Copy_File_Undo"
command is used to
remove a copy of a file from a change.
See
.IR aecpu (1)
for more information.
.TP 8n
.B -DELta_NAme
.br
The
.I "\*(n) -DELta_NAme"
command is used to
add a symbolic name to a project delta.
See
.IR aedn (1)
for more information.
.TP 8n
.B -Develop_Begin
.br
The
.I "\*(n) -Develop_Begin"
command is used to
begin development of a change.
See
.IR aedb (1)
for more information.
.TP 8n
.B -Develop_Begin_Undo
.br
The
.I "\*(n) -Develop_Begin_Undo"
command is used to
cease development of a change.
See
.IR aedbu (1)
for more information.
.TP 8n
.B -Develop_End
.br
The
.I "\*(n) -Develop_End"
command is used to
complete development of a change.
See
.IR aede (1)
for more information.
.TP 8n
.B -Develop_End_Undo
.br
The
.I "\*(n) -Develop_End_Undo"
command is used to
recall a change for further development.
See
.IR aedeu (1)
for more information.
.TP 8n
.B -DIFFerence
.br
The
.I "\*(n) -DIFFerence"
command is used to
find differences between development directory and baseline.
See
.IR aed (1)
for more information.
.so o_help.so
.TP 8n
.B -Integrate_Begin
.br
The
.I "\*(n) -Integrate_Begin"
command is used to
begin integrating a change.
See
.IR aeib (1)
for more information.
.TP 8n
.B -Integrate_Begin_Undo
.br
The
.I "\*(n) -Integrate_Begin_Undo"
command is used to
cease integrating a change.
See
.IR aeibu (1)
for more information.
.TP 8n
.B -Integrate_Fail
.br
The
.I "\*(n) -Integrate_Fail"
command is used to
fail a change integration.
See
.IR aeifail (1)
for more information.
.TP 8n
.B -Integrate_Pass
.br
The
.I "\*(n) -Integrate_PASS"
command is used to
pass a change integration.
See
.IR aeipass (1)
for more information.
.TP 8n
.B -List
.br
The
.I "\*(n) -List"
command is used to
list interesting things.
See
.IR ael (1)
for more information.
.TP 8n
.B -MoVe_file
.br
The
.I "\*(n) -MoVe_file"
command is used to
change the name of a file
as part of a change.
See
.IR aemv (1)
for more information.
.TP 8n
.B -MoVe_file_Undo
.br
The
.I "\*(n) -MoVe_file_Undo"
command is used to undo a
change to the name of a file
as part of a change.
See
.IR aemvu (1)
for more information.
.TP 8n
.B -New_Administrator
.br
The
.I "\*(n) -New_Administrator"
command is used to
add new administrators to a project.
See
.IR aena (1)
for more information.
.TP 8n
.B -New_BRanch
.br
The
.I "\*(n) -New_BRanch"
command is used to
add a new branch to a project.
See
.IR aenbr (1)
for more information.
.TP 8n
.B -New_BRanch_Undo
.br
The
.I "\*(n) -New_BRanch_Undo"
command is used to
remove a new branch from a project.
See
.IR aenbru (1)
for more information.
.TP 8n
.B -New_Change
.br
The
.I "\*(n) -New_Change"
command is used to
add a new change to a project.
See
.IR aenc (1)
for more information.
.TP 8n
.B -New_Change_Undo
.br
The
.I "\*(n) -New_Change_Undo"
command is used to
remove a new change from a project.
See
.IR aencu (1)
for more information.
.TP 8n
.B -New_Developer
.br
The
.I "\*(n) -New_Developer"
command is used to add
new developers to a project.
See
.IR aend (1)
for more information.
.TP 8n
.B -New_File
.br
The
.I "\*(n) -New_File"
command is used to
add new files to a change.
See
.IR aenf (1)
for more information.
.TP 8n
.B -New_File_Undo
.br
The
.I "\*(n) -New_File_Undo"
command is used to
remove new files from a change.
See
.IR aenfu (1)
for more information.
.TP 8n
.B -New_Integrator
.br
The
.I "\*(n) -New_Integrator"
command is used to
add new integrators to a project.
See
.IR aeni (1)
for more information.
.TP 8n
.B -New_Project
.br
The
.I "\*(n) -New_Project"
command is used to
create a new project to be watched over by \*(n).
See
.IR aenpr (1)
for more information.
.TP 8n
.B "-New_Project_Alias"
.br
The
.I "\*(n) -New_Project_Alias"
command is used to
create a new project alias.
See
.IR aenpa (1)
for more information.
.TP 8n
.B -New_ReLeaSe
.br
The
.I "\*(n) -New_ReLeaSe"
command is used to
create a new project from an existing project.
See
.IR aenrls (1)
for more information.
.TP 8n
.B -New_ReViewer
.br
The
.I "\*(n) -New_ReViewer"
command is used to
add new reviewers to a project.
See
.IR aenrv (1)
for more information.
.TP 8n
.B -New_Test
.br
The
.I "\*(n) -New_Test"
command is used to
add a new test to a change.
See
.IR aent (1)
for more information.
.TP 8n
.B -New_Test_Undo
.br
The
.I "\*(n) -New_Test_Undo"
command is used to
remove new tests from a change.
See
.IR aentu (1)
for more information.
.TP 8n
.B -Project_Attributes
.br
The
.I "\*(n) -Project_Attributes"
command is used to
modify the attributes of a project.
See
.IR aepa (1)
for more information.
.TP 8n
.B -Remove_Administrator
.br
The
.I "\*(n) -Remove_Administrator"
command is used to
remove administrators from a project.
See
.IR aera (1)
for more information.
.TP 8n
.B -Remove_Developer
.br
The
.I "\*(n) -Remove_Developer"
command is used to
remove developers from a project.
See
.IR aerd (1)
for more information.
.TP 8n
.B -ReMove_file
.br
The
.I "\*(n) -ReMove_file"
command is used to
add files to be deleted to a change.
See
.IR aerm (1)
for more information.
.TP 8n
.B -ReMove_file_Undo
.br
The
.I "\*(n) -Remove_File_Undo"
command is used to
remove files to be deleted from a change.
See
.IR aermu (1)
for more information.
.TP 8n
.B -Remove_Integrator
.br
The
.I "\*(n) -Remove_Integrator"
command is used to
remove integrators from a project.
See
.IR aeri (1)
for more information.
.TP 8n
.B -ReMove_PRoject
.br
The
.I "\*(n) -ReMove_PRoject"
command is used to
remove a project.
See
.IR aermpr (1)
for more information.
.TP 8n
.B -Remove_Project_Alias
.br
The
.I "\*(n) -Remove_Project_Alias"
command is used to
remove a project alias.
See
.IR aerpa (1)
for more information.
.TP 8n
.B -Remove_ReViewer
.br
The
.I "\*(n) -Remove_ReViewer"
command is used to
remove reviewers from a project.
See
.IR aerrv (1)
for more information.
.TP 8n
.B -RePorT
.br
The
.I "\*(n) -RePorT"
command is used to
generate reports from \*(n)' database.
These reports may be written by users,
or be distributed with \*(n).
.TP 8n
.B -Review_Fail
.br
The
.I "\*(n) -Review_Fail"
command is used to
fail a change review.
See
.IR aerfail (1)
for more information.
.TP 8n
.B -Review_Begin
.br
The
.I "\*(n) -Review_Begin"
command is used to
begin to review a change.
See
.IR aerb (1)
for more information.
.TP 8n
.B -Review_Begin_Undo
.br
The
.I "\*(n) -Review_Begin_Undo"
command is used to stop reviewing a change.
See
.IR aerbu (1)
for more information.
.TP 8n
.B -Review_Pass
.br
The
.I "\*(n) -Review_PASS"
command is used to
pass a change review.
See
.IR aerpass (1)
for more information.
.TP 8n
.B -Review_Pass_Undo
.br
The
.I "\*(n) -Review_Pass_Undo"
command is used to
rescind a change review pass.
See
.IR aerpu (1)
for more information.
.TP 8n
.B -Test
.br
The
.I "\*(n) -Test"
command is used to
run tests.
See
.IR aet (1)
for more information.
.TP 8n
.B -VERSion
.br
The
.I "\*(n) -VERSion"
command is used to
get copyright and version details.
See
.IR aev (1)
for more information.
.PP
All function selectors are case insensitive.
Function selectors may be abbreviated;
the abbreviation is the upper case letters.
Function selectors must appear as the first command line argument.
.SS Notification
Many \fIaegis\fP commands are capable of notification that they have
been run.  The individual commands document those specific to them.
For documentation on the various configurable notifications, see
\fIaepconf\fP(5) and \fIaepattr\fP(5) for more information.
.SH OPTIONS
The following options are available to all functions.
These options may appear anywhere on the command line following
the function selectors.
.so o_lib.so
.so o_verbose.so
.PP
The following options are available to
.I most
functions.
These options may appear anywhere on the command line following
the function selectors.
.so o_project.so
.TP 8n
\fB\-Change\fP \fInumber\fP
This option may be used to specify a particular change within a project.
When no
.B -Change
option is specified,
the
.I AEGIS_CHANGE
environment variable is consulted.
If that does not exist,
the user's
.I $HOME/.aegisrc
file is examined for a default change field (see
.IR aeuconf (5)
for more information).
If that does not exist,
when the user is only working on one change within a project,
that is the default change number.
Otherwise,
it is an error.
.TP 8n
\fB\-Change\fP \fIproject\fP\fB\.C\fInumber\fP
As a shortcut, it is possible to combine the \fB-\Project\fP and
\fB\-Change\fP options into a single option.
.TP 8n
\fB\-Change\fP \fIbranch\fP\fB\.C\fInumber\fP
Several functions accept a \fB\-BRanch\fP option; it is possible to
combine the \fB\-BRanch\fP and \fB\-Change\fP options in a single option.
(This intentinally has the same form as the \fI${version}\fP substitution
output for incomplete changes.)
.TP 8n
\fB\-Change\fP \fIbranch\fP\fB\.D\fInumber\fP
Several functions accept both the \fB\-BRanch\fP and \fB\-Delta\fP options
(or \fB\-BRanch\fP and \fB\-Change-From-Delta\fP options); it is possible
to combine them in a single option.  (This intentinally has the same
form as the \fI${version}\fP substitution output for completed changes.)
.TP 8n
\fB\-Change\fP \fIproject\fP\fB\.D\fInumber\fP
It is possible to combine the \fB\-Project\fP and
\fB\-Change-From-Delta\fP options as a single option.
.TP 8n
\fB\-Change\fP \fIUUID\fP
Each completed change is assigned a globallay unique identifier (UUID).
You can specify a change by its 36-character UUID, or any unambiguous
leading predix of the UUID (it must be at least 4 characters, and not look
like a number).
.SH Listings
The following options are available to all listings.
These options may appear anywhere on the command line following
the function selectors.
.so o_page.so
.so o_terse.so
.so o_unforma.so
.SH Abbreviations
.ds R) no
.so o__rules.so
.SH EXIT STATUS
The
.I \*(n)
command will exit with a status of 1 on any error.
The
.I \*(n)
command will only exit with a status of 0 if there are no errors.
.br
.ne 1i
.SH ENVIRONMENT VARIABLES
The
.I \*(n)
command understands the following environment variables:
.TP 8n
AEGIS_PATH
A colon-separated list of library directories.
See the
.B -LIBrary
option for a description how this environment variable is used.
.TP 8n
AEGIS_PROJECT
Names a default project.
See the
.B -Project
option for a description how this environment variable is used.
.TP 8n
AEGIS_CHANGE
Specifies a default change.
See the
.B -Change
option for a description how this environment variable is used.
.TP 8n
AEGIS_FLAGS
This environment variable is used to hold
.IR aeuconf (5)
information,
and over-rides the settings in the users
.I \&.aegisrc
file.
This is intended to be used within the tests distributed with aegis,
but can also be of use within some shell scripts.
.TP 8n
AEGIS_THROTTLE
Specifies the number of seconds to delay execution within commands
which set time stamps.
This is intended to be used within the tests distributed with aegis,
but can also be of use within some shell scripts.
.TP 8n
AEGIS_AUTOMOUNT_POINTS
.RS
A colon-separated list of directories which the automounter may use
to mount file systems.  Use with extreme care, as this distorts Aegis'
idea of the shape of the filesystem.
.PP
This feature assumes
that paths below the automounter's mount directory are echoes of paths
without it.
\fIE.g.\fP When \f[CW]/home\fP is the trigger, and
\f[CW]/tmp_mnt/home\fP is where the on-demand NFS mount is performed, with
\f[CW]/home\fP appearing to processes to be a symlink.
.PP
This is the behavior of the Sun automounter.  The AMD automounter is
capable of being configured in this way, though it is not typical of the
examples in the manual.  Nor is it typical of the out-of-the-box Linux
AMD configuration in many distributions.
.RE
.TP 8n
COLS
Specifies the page width for errors and listings.
See the
.B -Page_Width
option for a description how this environment variable is used.
.TP 8n
EDITOR
Specifies the program use to edit files when
the
.B -Edit
or
.B -Edit_BackGround
options are used.
(See also the
.I VISUAL
environment variable.)
Defaults to
.I vi
if not set.
See the \fIeditor_\%command\fP fields in \fIaeuconf\fP(1) for how to
override this specifically for Aegis.
.TP 8n
LINES
Specifies the page length for listings.
See the
.B -Page_Length
option for a description how this environment variable is used.
.TP 8n
PAGER
Specifies the program to use to view listings and help.
Not used if output is to a file or a pipe.
Defaults to
.I "more"
if not set.
.TP 8n
VISUAL
Specifies the program use to edit files when
the
.B -Edit
option is used.
(See also the
.I EDITOR
environment variable.)
Defaults to
.I vi
if not set.
See the \fIvisual_\%command\fP fields in \fIaeuconf\fP(1) for how to
override this specifically for Aegis.
.TP 8n
AEGIS_DATADIR
Overrides the datadir as specified at \fIconfigure\fP invocation.
Useful mainly for testing.
.so z_cmd_env.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aegis (5)
\*(n) file format syntax
.TP 8n
.IR aecattr (5)
change attributes file format
.TP 8n
.IR aecstate (5)
change state file format
.TP 8n
.IR aedir (5)
directory structures
.TP 8n
.IR aegstate (5)
\*(n) state file format
.TP 8n
.IR aepattr (5)
project attributes file format
.TP 8n
.IR aepconf (5)
project configuration file format
.TP 8n
.IR aepstate (5)
project state file format
.TP 8n
.IR aer (5)
report script language definition
.TP 8n
.IR aesub (5)
available command substitutions
.TP 8n
.IR aeuconf (5)
user configuration file format
.TP 8n
.IR aeustate (5)
user state file format
.so z_cr.so
