'\" tp
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991-2008 Peter Miller
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program. If not, see
.\"	<http://www.gnu.org/licenses/>.
.\"
.so z_name.so
.TH "\*(n) -Integrate_Fail" 1 \*(N) "Reference Manual"
.SH NAME
\*(n) -Integrate_Fail \- fail a change integration
.XX "aeifail(1)" "fail a change integration"
.SH SYNOPSIS
.B \*(n)
.B -Integrate_Fail
.B -File
.I reason-file
[
.IR option ...
]
.br
.B \*(n)
.B -Integrate_Fail
.B -REASon
.I "'reason-text'"
[
.IR option ...
]
.br
.B \*(n)
.B -Integrate_Fail
.B -Edit
[
.IR option ...
]
.br
.B \*(n)
.B -Integrate_Fail
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -Integrate_Fail
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -Integrate_Fail
command is used to
inform \*(n) that a change has failed integration.
.PP
The change will be returned
from the
.I "being integrated"
state to the
.I "being developed"
state.
The change will cease to be assigned to the current user,
and will be reassigned to the originating developer.
The integration directory will be deleted.
.\" ------------------------------------------------------------------------
.PS
boxwid = 1
down
S2: box "being" "developed"
arrow " develop" ljust " end" ljust
box "awaiting" "review"
arrow " review" ljust " begin" ljust
box "being" "reviewed"
arrow " review" ljust " pass" ljust
box "awaiting" "integration"
arrow " integrate" ljust " begin" ljust
S5: box "being" "integrated"

T7: spline -> from S5.e then right 0.5 then up 4 then to S2.e
"integrate " rjust "fail " rjust at T7.c + (0.5,0)
.PE
.\" ------------------------------------------------------------------------
.PP
The reviewer and the developer will be notified by mail.
See the integrate_fail_notify_command in
.IR aepconf (5)
for more information.
.PP
The
.I reason-file
will contain a description of why the change was failed.
The file is in plain text.
It is recommended that you only use newline to terminate paragraphs,
(rather than to terminate lines)
as with will result in better formatting in the various listings.
.SS Notification
On successful completion of this command, the
\fIintegrate_\%fail_\%notify_\%command\fP field of the project
attributes is run, if set.  See \fIaepattr\fP(5) and \fIaepa\fP(1)
for more information.
.SH OPTIONS
The following options are understood:
.so o_change.so
.so o_edit.so
.so o_file.so
.so o_help.so
.so o_keep.so
.so o_list.so
.so o_project.so
.so o_reason.so
.so o_terse.so
.so o_verbose.so
.so o_wait.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aeifail '\*(n) -ifail \e!* -v'
sh$	aeifail(){\*(n) -ifail "$@" -v}
.fi
.SH ERRORS
It is an error if
the change is not in the
.I "being integrated"
state.
.br
It is an error if
the change is not assigned to the current user.
.so z_exit.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aeib (1)
begin integration of a change
.TP 8n
.IR aeipass (1)
pass integration of a change
.TP 8n
.IR aeuconf (5)
user configuration file format
.so z_cr.so
