'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993, 1994, 1999 Peter Miller;
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
.\"
.\" MANIFEST: manual entry for 'aegis -List' command
.\"
.so z_name.so
.TH "\*(n) -List" 1 \*(N) "Reference Manual"
.SH NAME
\*(n) -List \- list (possibly) interesting things
.XX "ael(1)" "list interesting things"
.SH SYNOPSIS
.B \*(n)
.B -List
[
.IR option ...
]
.I list-name
.br
.B \*(n)
.B -List
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -List
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -List
command is used to
list information.
There are a number of possible
.IR list-name s,
as follows (abbreviations as for command line options):
.TP 8n
Administrators
.br
List the administrators of a project.
.TP 8n
Change_Details
.br
List full information about a change
in large format.
.TP 8n
Change_Files
.br
List all files in a change.
.TP 8n
Change_History
.br
List the history of a change.
.TP 8n
Changes
.br
List the changes of a project.
.TP 8n
Default_Change
.br
List the default change for the current user.
.TP 8n
Default_Project
.br
List the default project for the current user.
.TP 8n
Developers
.br
List the developers of a project.
.TP 8n
Integrators
.br
List the integrators of a project.
.TP 8n
List_List
.br
List all lists available.
.TP 8n
Locks
.br
List all currently active locks.
.TP 8n
Outstanding_Changes
.br
List all changes not yet completed.
.TP 8n
All_Outstanding_Changes
.br
List all changes not yet completed, for all projects.
.TP 8n
Project_Files
.br
List all files in the baseline of a project.
.TP 8n
Project_History
.br
List the integration history of a project.
.TP 8n
Projects
.br
List all projects.
.TP 8n
Project_Aliases
.br
List all project aliases.
.TP 8n
Reviewers
.br
List the reviewers of a project.
.TP 8n
State_File_Name
.br
Prints the absolute path of the project's or change's state file.
Useful for cookbooks and makefiles.
.TP 8n
Users_Changes
.br
List of changes owned by the current user.
.TP 8n
Version
.br
List version of a project or change.
This includes the major and minor version number,
and the previous version number if available.
The list of copyright years is also printed.
.PP
Most of these lists are available from other \*(n) functions.
Many \*(n) functions provide more specific lists.
.SH OPTIONS
The following options are understood:
.so o_change.so
.so o_help.so
.so o_list.so
.so o_page.so
.so o_project.so
.so o_terse.so
.so o_unforma.so
.so o_verbose.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias ael '\*(n) -l \e!* -v'
sh$	ael(){\*(n) -l $* -v}
.fi
.SH ERRORS
It is an error if
the list name given is unknown.
.so z_exit.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aedb (1)
begin development of a change (listing option)
.TP 8n
.IR aeib (1)
begin integration of a change (listing option)
.TP 8n
.IR aer (1)
report generator
.TP 8n
.IR aerpass (1)
pass review of a change (listing option)
.TP 8n
.IR aeuconf (5)
user configuration file format
.so z_cr.so
