'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993, 1995, 1996, 1998, 1999 Peter Miller;
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
.\"
.\" MANIFEST: manual entry for 'aegis -New_Change' command
.\"
.so z_name.so
.TH "\*(n) -New_Change" 1 \*(N) "Reference Manual"
.SH NAME
\*(n) -New_Change \- add a new change to a project
.XX "aenc(1)" "add a new change to a project"
.SH SYNOPSIS
.B \*(n)
.B -New_Change
[
.I number
]
.B -File
.I attr-file
[
.IR option ...
]
.br
.B \*(n)
.B -New_Change
[
.I number
]
.B -Edit
[
.IR option ...
]
.br
.B \*(n)
.B -New_Change
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -New_Change
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -New_Change
command is used to
add a new change to a project.
See
.IR aecattr (5)
for information on the format of the
.IR attr-file .
.PP
The change is created in the
.I "awaiting development"
state.
The change is not assigned to any user.
The change has no development directory.
.PP
You may choose your own change number if you want,
provided that it has not been used already.
If you do not specify a change number,
\*(n) will allocate the lowest unused change number.
The first few change numbers are reserved for
branches later in the project,
and so automatically allocated change
numbers will usually not start from 1. 
See
.IR aepa (1)
and
.IR aepattr (5)
for more information.
.SH OPTIONS
The following options are understood:
.so o_edit.so
.so o_file.so
.so o_help.so
.so o_list.so
.TP 8n
\fB\-Output\fP \fIfilename\fP
This option may be used to specify a filename which is to be written with
the automatically determined change number.  Useful for writing scripts.
.so o_project.so
.so o_terse.so
.so o_verbose.so
.so o_wait.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aenc '\*(n) -nc \e!* -v'
sh$	aenc(){\*(n) -nc $* -v}
.fi
.SH ERRORS
It is an error if
the current user is not an administrator of the project.
(In some cases it is possible for developers of a project to create
changes,
see 
.IR aepattr (5)
for more information.)
.so z_exit.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aeca (1)
modify the attributes of a change
.TP 8n
.IR aedb (1)
begin development of a change
.TP 8n
.IR aena (1)
add a new administrator to a project
.TP 8n
.IR aencu (1)
remove a new change from a project
.TP 8n
.IR aenpr (1)
create a new project
.TP 8n
.IR aepa (1)
modify the attributes of a project
.TP 8n
.IR aecattr (5)
change attributes file format
.TP 8n
.IR aepattr (5)
project attributes file format
.TP 8n
.IR aeuconf (5)
user configuration file format
.so z_cr.so
