'\" t
.\" aegis - project change supervisor
.\" Copyright (C) 1991-1993, 1998, 2003, 2006-2008, 2010, 2012 Peter Miller
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.so lib/en/man1/z_name.so
.TH "\*(n) \-New_ReViewer" 1 \*(N) "Reference Manual"
.SH NAME
aegis new reviewer \- add new reviewers to a project
.XX "aenrv(1)" "add new reviewers to a project"
.SH SYNOPSIS
.B \*(n)
.B \-New_ReViewer
.IR user\[hy]name ...
[
.IR option ...
]
.br
.B \*(n)
.B \-New_ReViewer
.B \-List
[
.IR option ...
]
.br
.B \*(n)
.B \-New_ReViewer
.B \-Help
.SH DESCRIPTION
The
.I \*(n)
.I \-New_ReViewer
command is used to
add new reviewers to a project.
.SH OPTIONS
The following options are understood:
.so lib/en/man1/o_help.so
.so lib/en/man1/o_list.so
.so lib/en/man1/o_project.so
.so lib/en/man1/o_recurse.so
.so lib/en/man1/o_terse.so
.so lib/en/man1/o_verbose.so
.so lib/en/man1/o_wait.so
.so lib/en/man1/o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%    alias aenrv '\*(n) \-nrv \e!* \-v'
sh$     aenrv(){\*(n) \-nrv "$@" \-v}
.fi
.SH ERRORS
It is an error if
the current user is not an administrator of the project.
.so lib/en/man1/z_exit.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aerrv (1)
remove reviewers from a project
.TP 8n
.IR aeuconf (5)
user configuration file format
.so lib/en/man1/z_cr.so
.\" vim: set ts=8 sw=4 et :
