'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991-1993, 1998, 2002, 2006-2008 Peter Miller
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program. If not, see
.\"	<http://www.gnu.org/licenses/>.
.\"
.so z_name.so
.TH "\*(n) -ReMove_PRoject" 1 \*(N) "Reference Manual"
.SH NAME
\*(n) -ReMove_PRoject \- remove project
.XX "aermpr(1)" "remove project"
.SH SYNOPSIS
.B \*(n)
.B -ReMove_Project
.I project-name
[
.IR option \&...
]
.br
.B \*(n)
.B -ReMove_Project
.B -List
[
.IR option \&...
]
.br
.B \*(n)
.B -ReMove_Project
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -ReMove_PRoject
command is used to
remove a project, either entirely,
or just from \*(n)' supervision.
.PP
Project aliases to the removed project are also removed.
.SH OPTIONS
The following options are understood:
.so o_help.so
.so o_interact.so
.so o_keep.so
.so o_lib.so
.so o_list.so
.so o_project.so
.so o_terse.so
.so o_verbose.so
.so o_wait.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aermpr '\*(n) -rmpr \e!* -v'
sh$	aermpr(){\*(n) -rmpr "$@" -v}
.fi
.SH ERRORS
It is an error if
the project has any changes between the
.I "being developed"
and
.I "being integrated"
states,
inclusive.
.br
It is an error if
the current user is not an administrator.
.so z_exit.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aenpr (1)
create a new project
.TP 8n
.IR aenrls (1)
create a new project from an existing project
.so z_cr.so
