'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 1991, 1992, 1993, 1998, 1999 Peter Miller;
.\"	All rights reserved.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111, USA.
.\"
.\" MANIFEST: manual entry for the 'aegis -Review_PASS' command
.\"
.so z_name.so
.TH "\*(n) -Review_PASS" 1 \*(N) "Reference Manual"
.SH NAME
\*(n) -Review_PASS \- pass a change review
.XX "aerpass(1)" "pass a change review"
.SH SYNOPSIS
.B \*(n)
.B -Review_PASS
[
.IR option ...
]
.br
.B \*(n)
.B -Review_PASS
.B -List
[
.IR option ...
]
.br
.B \*(n)
.B -Review_PASS
.B -Help
.SH DESCRIPTION
The
.I \*(n)
.I -Review_PASS
command is used to
notify \*(n) that a change has passed review.
.PP
The change will be advanced from the
.I "being reviewed"
state to the
.I "awaiting integration"
state.
.SH OPTIONS
The following options are understood:
.so o_change.so
.so o_help.so
.so o_list.so
.so o_project.so
.so o_terse.so
.so o_verbose.so
.so o_wait.so
.so o__rules.so
.SH RECOMMENDED ALIAS
The recommended alias for this command is
.nf
.ta 8n 16n
csh%	alias aerpass '\*(n) -rpass \e!* -v'
sh$	aerpass(){\*(n) -rpass $* -v}
.fi
.SH ERRORS
It is an error if
the change is not in the
.I "being reviewed"
state.
.br
It is an error if
the current user is not a reviewer of the project.
.br
Its is an error if
the current user developed the change and the project is configured to
disallow developers to review their own changes (default).
.so z_exit.so
.br
.ne 1i
.SH SEE ALSO
.TP 8n
.IR aecd (1)
change directory
.TP 8n
.IR aede (1)
complete development of a change
.TP 8n
.IR aedeu (1)
recall a change for further development
.TP 8n
.IR aeib (1)
begin integrating a change
.TP 8n
.IR aenrv (1)
add a reviewer to a project
.TP 8n
.IR aerfail (1)
fail review of a change
.TP 8n
.IR aerpu (1)
rescind a change review pass
.TP 8n
.IR aeuconf (5)
user configuration file format
.so z_cr.so
