'\" t
.\"	aegis - project change supervisor
.\"	Copyright (C) 2005-2008 Peter Miller
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program. If not, see
.\"	<http://www.gnu.org/licenses/>.
.\"
.so z_name.so
.ds n) aexver
.TH "aexver" 1 \*(N) "Reference Manual" ""
.SH NAME
aexver \- graphical file history
.XX "aexver(1)" "graphical file history"
.SH SYNOPSIS
\fB\*(n)\fP
.SH DESCRIPTION
The \fI\*(n)\fP command is used to to view historical versions of files
in an Aegis repository.
.PP
A list box is displayed with all project filenames in it.
When ther user double-clicks on a file, another box is displayed
listing all the revisions of that file.
Selecting any two revisions will bring up a diff comparing
those revisions to each other.
.SH ENVIRONMENT VARIABLES
.TP 8n
AE2DIFF
The name of the program to perform the 2-way diff.
Default to \f[CW]xidff\fP if not set.
.so z_exit.so
.so z_cr.so
