.\"
.\"     aegis - project change supervisor
.\"     Copyright (C) 1995-1999, 2004, 2006-2009, 2012 Peter Miller
.\"
.\"     This program is free software; you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation; either version 3 of the License, or
.\"     (at your option) any later version.
.\"
.\"     This program is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\"
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program. If not, see
.\"     <http://www.gnu.org/licenses/>.
.\"
.\" LSM = Linux Software Module, an archive description file
.\"
.\" Descriptions of the LSM file format can be found in the
.\" /pub/Linux/docs directories of sunsite.unc.edu and tsx-11.mit.edu.
.\"
.ad l
.hy 0
.de SH
.in 0
.br
\\$1
'in 8n
..
.so etc/version.so
.SH Begin3
.SH Title:
Aegis
.SH Version:
\*(v)
.SH Entered-date:
.ds MO1 JAN
.ds MO2 FEB
.ds MO3 MAR
.ds MO4 APR
.ds MO5 MAY
.ds MO6 JUN
.ds MO7 JUL
.ds MO8 AUG
.ds MO9 SEP
.ds MO10 OCT
.ds MO11 NOV
.ds MO12 DEC
.nr y4 \n[yr]+1900
\n[dy]\*[MO\n[mo]]\n[y4]
.SH Description:
Aegis is a transaction-based software configuration management system.
It provides a framework within which
a team of developers may work on many changes to a
program independently, and Aegis coordinates integrating
these changes back into the master source of the program,
with as little disruption as possible.
.sp
Aegis supports geographically distributed development.  A very flexible
mechanism is provided which may be used to keep two or more repositories
synchronized.
.sp
Aegis runs on almost any flavor of UNIX.
Self configuring using a script generated by GNU Autoconf.
There are no modifications required to compile it for Linux.
.SH Keywords:
transaction based software configuration management,
software configuration management,
SCM,
version control
.SH Author:
pmiller@opensource.org.au (Peter Miller)
.SH Primary-site:
http://miller.emu.id.au/pmiller/
.TS
tab(;);
l l.
aegis-\*(v).README;Description, from the tar file
aegis-\*(v).lsm;Description, in LSM format
aegis-\*(v).ae;the complete source, aedist format
aegis-\*(v).tar.gz;the complete source
aegis-\*(v).spec;RedHat package specification
aegis-\*(v).faq;Frequently asked questions, with answers
aegis-\*(v).ug.ps.gz;User Guide, PostScript format
aegis-\*(v).rm.ps.gz;Reference Manual, PostScript format
.TE
.SH Secondary-site:
ftp://sunsite.unc.edu/pub/Linux/devel/vc
.TS
tab(;);
l l.
aegis-\*(v).README;Description, from the tar file
aegis-\*(v).lsm;Description, in LSM format
aegis-\*(v).ae;the complete source, aedist format
aegis-\*(v).tar.gz;the complete source
aegis-\*(v).spec;RedHat package specification
aegis-\*(v).faq;Frequently asked questions, with answers
aegis-\*(v).ug.ps.gz;User Guide, PostScript format
aegis-\*(v).rm.ps.gz;Reference Manual, PostScript format
.TE
.SH Copying-policy:
GPL
.SH End
.\" vim: set ts=8 sw=4 et :
